name: Buffered
version: '${project.version}'
main: sh.astrid.buffered.Buffered
api-version: "1.20"
load: STARTUP
authors: [Astrid]
depend: [WorldGuard]
description: KitPvP core for Buffered.
website: https://astrid.sh/
