[tags.galaxy]
displayName = "Galaxy"
tag = "<#c691ff><bold>₊✧˚<reset>"

[tags.egirl]
displayName = "EGirl"
tag = "<p><s>[</s>EGirl<s>]<reset>"

[tags.linked]
displayName = "Linked"
tag = "<l>⚔<reset>"
earnDescription = "<t><bold>»</bold> /link <bold>«</bold>"